import { inter } from '@/app/fonts/fonts';
import { NavigationSection } from '@/components/sections/NavigationSection/NavigationSection';
import { Toaster } from "@/components/ui/sonner";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import "../globals.css";
import FooterSection from '@/components/sections/FooterSection/FooterSection';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}>) {

  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${inter.className} antialiased select-none overflow-x-hidden`}>
          <NextIntlClientProvider>
            <main>
              {/* Header */}
              <NavigationSection />

              {children}

              {/* Footer */}
              <FooterSection />
            </main>
            <Toaster />
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
