import type { Metadata } from "next";
import { inter } from '@/app/fonts/fonts';
import "../globals.css";
import { routing } from "@/i18n/routing";
import { Language } from "@/types";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}>) {

  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${inter.className} antialiased select-none`}>
          <NextIntlClientProvider>
            <main className='overflow-x-hidden'>
              {/* Header */}
              {/** <Header /> */}

              {children}

              {/* Footer */}
              {/** <Footer /> */}
            </main>
            <Toaster />
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
